apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "president.fullname" . }}-game-server
  labels:
    app: {{ include "president.name" . }}-game-server
spec:
  replicas: {{ .Values.gameServer.replicas }}
  selector:
    matchLabels:
      app: {{ include "president.name" . }}-game-server
  template:
    metadata:
      labels:
        app: {{ include "president.name" . }}-game-server
    spec:
      containers:
        - name: game-server
          image: {{ .Values.gameServer.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 2567
          env:
            - name: NODE_ENV
              value: {{ .Values.gameServer.nodeEnv }}
            - name: REDIS_URL
              value: "redis://{{ include "president.fullname" . }}-redis:6379"
            - name: BACK_URL
              value: "http://{{ include "president.fullname" . }}-back"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "president.fullname" . }}-game-server
  labels:
    app: {{ include "president.name" . }}-game-server
spec:
  type: LoadBalancer
  ports:
    - port: 2567
      targetPort: 2567
  selector:
    app: {{ include "president.name" . }}-game-server
